# Generated by Django 5.2.10 on 2026-01-23 19:15

from django.db import migrations


def remove_staff_from_hr_users(apps, schema_editor):
    """
    Remove staff status from all HR users.
    Only superusers should have staff access to Django Admin.
    """
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Find all HR users who have staff status
    hr_users = CustomUser.objects.filter(is_hr=True, is_staff=True, is_superuser=False)
    
    # Remove staff status
    count = hr_users.update(is_staff=False)
    
    if count > 0:
        print(f"Removed staff status from {count} HR user(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_staff_from_hr_users, reverse_code=migrations.RunPython.noop),
    ]
