# Generated by Django 5.2.10 on 2026-01-29 13:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_staff_from_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
