# Generated by Django 5.2.10 on 2026-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidateprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
