# Generated by Django 5.2.10 on 2026-01-31 10:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidateprofile_contact_candidateprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='master_resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
    ]
