# Generated by Django 5.2.10 on 2026-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_candidateprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
