# Generated by Django 5.2.10 on 2026-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_candidateprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Deadline for applications', null=True),
        ),
    ]
