# Generated by Django 5.2.10 on 2026-01-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobpost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated required skills'),
        ),
    ]
