# Generated by Django 5.2.10 on 2026-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_name',
            field=models.CharField(blank=True, help_text='e.g. Technical Assessment, HR Round', max_length=200, null=True),
        ),
    ]
