# Generated by Django 5.2.10 on 2026-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_interview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='RecruitAICorp', max_length=200),
        ),
    ]
