# Generated by Django 5.2.10 on 2026-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobpost_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='max_age',
            field=models.IntegerField(blank=True, help_text='Maximum age allowed', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='Minimum age required', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_degree_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum degree percentage required', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum 10th percentage required', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum 12th/Diploma percentage required', max_digits=5, null=True),
        ),
    ]
