# Generated by Django 5.2.10 on 2026-02-07 05:24

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_jobpost_max_age_jobpost_min_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('company_description', models.TextField(blank=True, help_text='Brief description of your company')),
                ('industry', models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('Finance', 'Finance & Banking'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail & E-commerce'), ('Consulting', 'Consulting'), ('Other', 'Other')], max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('location', models.CharField(blank=True, help_text='Company headquarters location', max_length=200)),
                ('contact', models.CharField(blank=True, help_text='Contact number', max_length=20)),
                ('website_url', models.URLField(blank=True, help_text='Company website', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Company LinkedIn page', null=True)),
                ('founded_year', models.IntegerField(blank=True, help_text='Year company was founded', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
